#!/usr/bin/env python3
"""Generate local agent configs from committed OpenCode source.

Usage:
    uv run python scripts/sync_agent_configs.py
    uv run python scripts/sync_agent_configs.py --force
    uv run python scripts/sync_agent_configs.py --target cursor
    uv run python scripts/sync_agent_configs.py --target claude
    uv run python scripts/sync_agent_configs.py --target copilot
    uv run python scripts/sync_agent_configs.py --target codex

Two rules keep the output loadable, and both were learned by breaking them.

**The provenance banner goes below the frontmatter, never above it.** Every
consumer here parses YAML frontmatter only when it opens the file — line one,
column one. A banner above it does not fail loudly: Cursor, Copilot, and
Claude Code all read the file and quietly get nothing. Claude Code skills
loaded for months with ``<!--`` as their description, and Claude Code agents
did not load at all.

**Frontmatter is translated per target, never copied.** ``.opencode/agents/``
is written in OpenCode's schema — ``mode``, ``steps``, ``temperature``, a
nested ``permission`` map, and a model name from OpenCode's catalogue. None of
that means anything to another runtime, and Claude Code additionally requires
a ``name`` OpenCode infers from the filename. The body is shared prose; the
frontmatter is not.
"""

from __future__ import annotations

import argparse
from collections.abc import Mapping
from pathlib import Path
from typing import Final, cast

import yaml

GENERATED_HEADER = """<!--
Generated by scripts/sync_agent_configs.py.
Source of truth: AGENTS.md and .opencode/.
Do not edit this file directly. Edit the OpenCode source files instead.
-->
"""

REPO_ROOT = Path(__file__).resolve().parent.parent

#: Claude Code tools reachable from each OpenCode permission key. A key absent
#: here has no Claude Code counterpart and is dropped rather than guessed at.
#: ``list`` folds into ``Glob`` because Claude Code has no separate listing
#: tool.
_CLAUDE_TOOLS_FOR_PERMISSION: Final[Mapping[str, tuple[str, ...]]] = {
    "read": ("Read",),
    "glob": ("Glob",),
    "list": ("Glob",),
    "grep": ("Grep",),
    "edit": ("Edit", "Write"),
    "todowrite": ("TodoWrite",),
    "bash": ("Bash",),
    "task": ("Agent",),
    "skill": ("Skill",),
    "webfetch": ("WebFetch",),
    "websearch": ("WebSearch",),
}

#: OpenCode model names mapped onto what Claude Code accepts. The fallback is
#: deliberately not the strongest model: these are routine-repair agents, and
#: ``AGENTS.md`` says not to spend premium tokens on lint and test loops.
_CLAUDE_MODEL_ALIASES: Final[Mapping[str, str]] = {
    "opencode-go/deepseek-v4-flash-free": "sonnet",
}
_CLAUDE_FALLBACK_MODEL: Final = "sonnet"


def read_agents_md() -> str:
    path = REPO_ROOT / "AGENTS.md"
    return path.read_text(encoding="utf-8") if path.exists() else ""


def read_opencode_skills() -> dict[str, str]:
    skills_dir = REPO_ROOT / ".opencode" / "skills"
    result: dict[str, str] = {}
    if skills_dir.is_dir():
        for skill_dir in sorted(skills_dir.iterdir()):
            skill_file = skill_dir / "SKILL.md"
            if skill_file.is_file():
                result[skill_dir.name] = skill_file.read_text(encoding="utf-8")
    return result


def read_opencode_agents() -> dict[str, str]:
    agents_dir = REPO_ROOT / ".opencode" / "agents"
    result: dict[str, str] = {}
    if agents_dir.is_dir():
        for agent_file in sorted(agents_dir.glob("*.md")):
            result[agent_file.stem] = agent_file.read_text(encoding="utf-8")
    return result


def split_frontmatter(document: str) -> tuple[str, str]:
    """Split *document* into its frontmatter block and the body after it.

    Returns ``("", document)`` when there is no frontmatter. The block is
    recognized only at the very start of the file, which is the same rule
    every consumer applies — a ``---`` further down is a horizontal rule.
    """
    if not document.startswith("---\n"):
        return "", document
    end = document.find("\n---\n", 3)
    if end == -1:
        return "", document
    boundary = end + len("\n---\n")
    return document[:boundary], document[boundary:]


def strip_frontmatter(document: str) -> str:
    """Return *document*'s body alone.

    Used where an OpenCode agent is embedded inside a frontmatter block this
    script writes for another runtime. Carrying the source frontmatter through
    would leave OpenCode's ``mode``/``permission`` keys sitting in the body as
    a stray ``---`` block — read by nothing, and read by a human as a second
    configuration that is in force.
    """
    return split_frontmatter(document)[1].lstrip("\n")


def banner(document: str) -> str:
    """Return *document* with the provenance banner where it cannot do harm.

    Below the frontmatter when there is any, at the top when there is not.
    Putting it above a frontmatter block is what silently disabled every
    generated skill and agent, so this function is the only place the banner
    is ever attached.
    """
    frontmatter, body = split_frontmatter(document)
    if not frontmatter:
        return f"{GENERATED_HEADER}{document}"
    return f"{frontmatter}{GENERATED_HEADER}{body}"


def frontmatter_fields(document: str) -> dict[str, object]:
    """Return *document*'s frontmatter as a mapping, empty when it has none."""
    raw = split_frontmatter(document)[0]
    return _as_mapping(yaml.safe_load(raw.strip("-\n")) if raw else None)


def skill_section(name: str, document: str) -> str:
    """Render a skill for a runtime that embeds it inside another document.

    Cursor rules, Copilot instructions, and the Codex README each wrap skills
    in a frontmatter block of their own, so the skill's block would land in the
    middle of the body: inert to the parser and, to a reader, a second
    configuration that looks like it is in force. The description is the one
    thing worth keeping, so it becomes prose instead of being dropped.
    """
    description = frontmatter_fields(document).get("description")
    heading = f"## {name}\n\n"
    if description:
        heading += f"{description}\n\n"
    return f"{heading}{strip_frontmatter(document)}"


def _as_mapping(value: object) -> dict[str, object]:
    """Return *value* as a string-keyed mapping, or an empty one.

    Hand-written YAML reaches here, so a key that is not a string is a typo in
    the source rather than something to reason about.
    """
    if not isinstance(value, dict):
        return {}
    raw = cast("dict[object, object]", value)
    return {key: item for key, item in raw.items() if isinstance(key, str)}


def _permits(value: object) -> bool:
    """Return whether an OpenCode permission value grants the tool at all.

    A plain ``allow``/``ask`` grants it and ``deny`` does not. A pattern map
    (``bash``, ``skill``) grants the tool when any pattern is not a denial:
    Claude Code's agent frontmatter has no per-command granularity, so the
    choice is the whole tool or none of it. **The pattern list itself does not
    survive translation** — command-level allow and deny lists belong in
    ``.claude/settings.json`` permissions, not here, and pretending otherwise
    would advertise a restriction that is not enforced.
    """
    if isinstance(value, str):
        return value != "deny"
    return any(_permits(entry) for entry in _as_mapping(value).values())


def claude_agent_tools(permission: object) -> list[str]:
    """Translate an OpenCode permission block into a Claude Code tool list."""
    granted: set[str] = set()
    for key, value in _as_mapping(permission).items():
        granted.update(_CLAUDE_TOOLS_FOR_PERMISSION.get(key, ()) if _permits(value) else ())
    return sorted(granted)


def claude_agent_document(name: str, source: str) -> str:
    """Rewrite one OpenCode agent into what Claude Code will actually load.

    Claude Code needs ``name`` (which OpenCode takes from the filename) and
    ``description``; it understands ``tools`` and ``model``, and nothing else
    in the source frontmatter. The body — the actual contract the agent
    follows — is carried through untouched.
    """
    raw, body = split_frontmatter(source)
    fields = _as_mapping(yaml.safe_load(raw.strip("-\n")) if raw else None)

    description = fields.get("description")
    header: dict[str, object] = {
        "name": name,
        "description": str(description) if description else f"The {name} agent.",
    }
    tools = claude_agent_tools(fields.get("permission"))
    if tools:
        header["tools"] = ", ".join(tools)
    model = fields.get("model")
    header["model"] = _CLAUDE_MODEL_ALIASES.get(str(model), _CLAUDE_FALLBACK_MODEL)

    rendered = yaml.safe_dump(header, sort_keys=False, allow_unicode=True, width=10_000)
    return banner(f"---\n{rendered}---\n{body}")


def write_generated(path: Path, content: str, force: bool) -> bool:
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def sync_cursor(
    agents_content: str,
    skills: dict[str, str],
    opencode_agents: dict[str, str],
    force: bool,
) -> list[str]:
    created: list[str] = []
    rules_dir = REPO_ROOT / ".cursor" / "rules"

    files: dict[str, str] = {
        "000-project.mdc": f"{GENERATED_HEADER}\n# Ferumind Project\n\n{agents_content[:500]}",
        "100-python.mdc": f"{GENERATED_HEADER}\n# Python Standards\n\n- Use Python 3.12+\n- Strict typing required\n- Use Pydantic v2 for configs\n- Use pathlib, not os.path\n- Line length 100\n- Ruff for linting/formatting",
        "200-testing.mdc": f"{GENERATED_HEADER}\n# Testing Standards\n\n- pytest for all tests\n- Coverage threshold 80%+\n- Use tmp_path for filesystem tests\n- Test success and failure paths\n- No mocking core behavior unnecessarily",
        "300-security.mdc": f"{GENERATED_HEADER}\n# Security Rules\n\n- No symlink escape\n- No `..` traversal\n- No absolute writes\n- All paths through core path validator\n- No hard delete of user content",
        "400-ferumind-architecture.mdc": f"{GENERATED_HEADER}\n# Ferumind Architecture\n\n{agents_content[:800]}",
    }

    for name, content in files.items():
        path = rules_dir / name
        if write_generated(path, content, force):
            created.append(str(path.relative_to(REPO_ROOT)))

    for skill_name, skill_content in skills.items():
        path = rules_dir / f"skill-{skill_name}.mdc"
        content = banner(
            "---\n"
            f"description: Use the {skill_name} skill when relevant.\n"
            "alwaysApply: false\n"
            "---\n\n"
            f"{skill_section(skill_name, skill_content)}"
        )
        if write_generated(path, content, force):
            created.append(str(path.relative_to(REPO_ROOT)))

    test_fixer = opencode_agents.get("test-fixer")
    if test_fixer is not None:
        path = rules_dir / "500-test-fixer.mdc"
        content = banner(
            "---\n"
            "description: Use when running verification or fixing failing tests, lint, or type checks.\n"
            "alwaysApply: false\n"
            "---\n\n"
            "# Ferumind Test Fixer\n\n"
            f"{strip_frontmatter(test_fixer)}"
        )
        if write_generated(path, content, force):
            created.append(str(path.relative_to(REPO_ROOT)))

    return created


def sync_claude(
    agents_content: str,
    skills: dict[str, str],
    opencode_agents: dict[str, str],
    force: bool,
) -> list[str]:
    created: list[str] = []

    claude_path = REPO_ROOT / "CLAUDE.md"
    if write_generated(claude_path, f"{GENERATED_HEADER}{agents_content}", force):
        created.append("CLAUDE.md")

    skills_base = REPO_ROOT / ".claude" / "skills"
    for skill_name, skill_content in skills.items():
        path = skills_base / skill_name / "SKILL.md"
        if write_generated(path, banner(skill_content), force):
            created.append(str(path.relative_to(REPO_ROOT)))

    agents_base = REPO_ROOT / ".claude" / "agents"
    for agent_name, agent_content in opencode_agents.items():
        path = agents_base / f"{agent_name}.md"
        if write_generated(path, claude_agent_document(agent_name, agent_content), force):
            created.append(str(path.relative_to(REPO_ROOT)))

    return created


def sync_copilot(
    agents_content: str,
    skills: dict[str, str],
    opencode_agents: dict[str, str],
    force: bool,
) -> list[str]:
    created: list[str] = []

    instructions_path = REPO_ROOT / ".github" / "copilot-instructions.md"
    if write_generated(
        instructions_path,
        f"{GENERATED_HEADER}# Ferumind — Copilot Instructions\n\n{agents_content[:1500]}",
        force,
    ):
        created.append(".github/copilot-instructions.md")

    instructions_dir = REPO_ROOT / ".github" / "instructions"
    for name, header in [
        ("python.instructions.md", "Python Standards"),
        ("testing.instructions.md", "Testing Standards"),
        ("security.instructions.md", "Security Rules"),
    ]:
        path = instructions_dir / name
        if write_generated(
            path, f"{GENERATED_HEADER}# {header}\n\nSee .github/copilot-instructions.md", force
        ):
            created.append(str(path.relative_to(REPO_ROOT)))

    for skill_name, skill_content in skills.items():
        path = instructions_dir / f"{skill_name}.instructions.md"
        content = banner(f'---\napplyTo: "**"\n---\n\n{skill_section(skill_name, skill_content)}')
        if write_generated(path, content, force):
            created.append(str(path.relative_to(REPO_ROOT)))

    for agent_name, agent_content in opencode_agents.items():
        if agent_name == "test-fixer":
            path = instructions_dir / "test-fixer.instructions.md"
            content = banner(
                "---\n"
                'applyTo: "**"\n'
                'excludeAgent: "code-review"\n'
                "---\n\n"
                "# Test Fix Agent Instructions\n\n"
                "Use these instructions when asked to run verification, fix failing tests, "
                "repair lint/typecheck failures, or make a branch green.\n\n"
                f"{strip_frontmatter(agent_content)}"
            )
            if write_generated(path, content, force):
                created.append(str(path.relative_to(REPO_ROOT)))

    return created


def sync_codex(
    skills: dict[str, str],
    opencode_agents: dict[str, str],
    force: bool,
) -> list[str]:
    created: list[str] = []
    readme_path = REPO_ROOT / ".codex" / "README.md"
    test_fixer = opencode_agents.get("test-fixer", "")
    skills_section = "\n\n".join(skill_section(name, content) for name, content in skills.items())
    content = (
        f"{GENERATED_HEADER}"
        "# Codex — Ferumind\n\n"
        "Use root `AGENTS.md` for project context.\n\n"
        "## Skills\n\n"
        f"{skills_section}\n\n"
        "When asked to make verification pass, follow the Test Fixer contract below.\n\n"
        f"{strip_frontmatter(test_fixer)}\n"
    )
    if write_generated(readme_path, content, force):
        created.append(".codex/README.md")
    return created


def main() -> None:
    parser = argparse.ArgumentParser(description="Sync agent configs from OpenCode source")
    parser.add_argument("--force", action="store_true", help="Overwrite existing generated files")
    parser.add_argument(
        "--target",
        choices=["cursor", "claude", "copilot", "codex", "all"],
        default="all",
        help="Target agent (default: all)",
    )
    args = parser.parse_args()

    agents_content = read_agents_md()
    skills = read_opencode_skills()
    opencode_agents = read_opencode_agents()

    targets = ["cursor", "claude", "copilot", "codex"] if args.target == "all" else [args.target]

    created: list[str] = []
    for target in targets:
        if target == "cursor":
            created.extend(sync_cursor(agents_content, skills, opencode_agents, args.force))
        elif target == "claude":
            created.extend(sync_claude(agents_content, skills, opencode_agents, args.force))
        elif target == "copilot":
            created.extend(sync_copilot(agents_content, skills, opencode_agents, args.force))
        elif target == "codex":
            created.extend(sync_codex(skills, opencode_agents, args.force))

    if created:
        print(f"Generated/updated {len(created)} file(s):")
        for path in created:
            print(f"  {path}")
    else:
        print("Nothing to update (all files already exist, use --force to overwrite)")


if __name__ == "__main__":
    main()
