#!/usr/bin/env python3
"""Generate local agent configs from committed OpenCode source.

Usage:
    uv run python scripts/sync_agent_configs.py
    uv run python scripts/sync_agent_configs.py --force
    uv run python scripts/sync_agent_configs.py --target cursor
    uv run python scripts/sync_agent_configs.py --target claude
    uv run python scripts/sync_agent_configs.py --target copilot
    uv run python scripts/sync_agent_configs.py --target codex
"""

from __future__ import annotations

import argparse
from pathlib import Path

GENERATED_HEADER = """<!--
Generated by scripts/sync_agent_configs.py.
Source of truth: AGENTS.md and .opencode/.
Do not edit this file directly. Edit the OpenCode source files instead.
-->
"""

REPO_ROOT = Path(__file__).resolve().parent.parent


def read_agents_md() -> str:
    path = REPO_ROOT / "AGENTS.md"
    return path.read_text(encoding="utf-8") if path.exists() else ""


def read_opencode_skills() -> dict[str, str]:
    skills_dir = REPO_ROOT / ".opencode" / "skills"
    result: dict[str, str] = {}
    if skills_dir.is_dir():
        for skill_dir in sorted(skills_dir.iterdir()):
            skill_file = skill_dir / "SKILL.md"
            if skill_file.is_file():
                result[skill_dir.name] = skill_file.read_text(encoding="utf-8")
    return result


def read_opencode_agents() -> dict[str, str]:
    agents_dir = REPO_ROOT / ".opencode" / "agents"
    result: dict[str, str] = {}
    if agents_dir.is_dir():
        for agent_file in sorted(agents_dir.glob("*.md")):
            result[agent_file.stem] = agent_file.read_text(encoding="utf-8")
    return result


def write_generated(path: Path, content: str, force: bool) -> bool:
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def sync_cursor(
    agents_content: str,
    skills: dict[str, str],
    opencode_agents: dict[str, str],
    force: bool,
) -> list[str]:
    created: list[str] = []
    rules_dir = REPO_ROOT / ".cursor" / "rules"

    files: dict[str, str] = {
        "000-project.mdc": f"{GENERATED_HEADER}\n# Lattice Project\n\n{agents_content[:500]}",
        "100-python.mdc": f"{GENERATED_HEADER}\n# Python Standards\n\n- Use Python 3.12+\n- Strict typing required\n- Use Pydantic v2 for configs\n- Use pathlib, not os.path\n- Line length 100\n- Ruff for linting/formatting",
        "200-testing.mdc": f"{GENERATED_HEADER}\n# Testing Standards\n\n- pytest for all tests\n- Coverage threshold 80%+\n- Use tmp_path for filesystem tests\n- Test success and failure paths\n- No mocking core behavior unnecessarily",
        "300-security.mdc": f"{GENERATED_HEADER}\n# Security Rules\n\n- No symlink escape\n- No `..` traversal\n- No absolute writes\n- All paths through core path validator\n- No hard delete of user content",
        "400-lattice-architecture.mdc": f"{GENERATED_HEADER}\n# Lattice Architecture\n\n{agents_content[:800]}",
    }

    for name, content in files.items():
        path = rules_dir / name
        if write_generated(path, content, force):
            created.append(str(path.relative_to(REPO_ROOT)))

    for skill_name, skill_content in skills.items():
        path = rules_dir / f"skill-{skill_name}.mdc"
        content = (
            f"{GENERATED_HEADER}"
            "---\n"
            f"description: Use the {skill_name} skill when relevant.\n"
            "alwaysApply: false\n"
            "---\n\n"
            f"{skill_content}"
        )
        if write_generated(path, content, force):
            created.append(str(path.relative_to(REPO_ROOT)))

    test_fixer = opencode_agents.get("test-fixer")
    if test_fixer is not None:
        path = rules_dir / "500-test-fixer.mdc"
        content = (
            f"{GENERATED_HEADER}"
            "---\n"
            "description: Use when running verification or fixing failing tests, lint, or type checks.\n"
            "alwaysApply: false\n"
            "---\n\n"
            "# Lattice Test Fixer\n\n"
            f"{test_fixer}"
        )
        if write_generated(path, content, force):
            created.append(str(path.relative_to(REPO_ROOT)))

    return created


def sync_claude(
    agents_content: str,
    skills: dict[str, str],
    opencode_agents: dict[str, str],
    force: bool,
) -> list[str]:
    created: list[str] = []

    claude_path = REPO_ROOT / "CLAUDE.md"
    if write_generated(claude_path, f"{GENERATED_HEADER}{agents_content}", force):
        created.append("CLAUDE.md")

    skills_base = REPO_ROOT / ".claude" / "skills"
    for skill_name, skill_content in skills.items():
        path = skills_base / skill_name / "SKILL.md"
        if write_generated(path, f"{GENERATED_HEADER}{skill_content}", force):
            created.append(str(path.relative_to(REPO_ROOT)))

    agents_base = REPO_ROOT / ".claude" / "agents"
    for agent_name, agent_content in opencode_agents.items():
        path = agents_base / f"{agent_name}.md"
        if write_generated(path, f"{GENERATED_HEADER}{agent_content}", force):
            created.append(str(path.relative_to(REPO_ROOT)))

    return created


def sync_copilot(
    agents_content: str,
    skills: dict[str, str],
    opencode_agents: dict[str, str],
    force: bool,
) -> list[str]:
    created: list[str] = []

    instructions_path = REPO_ROOT / ".github" / "copilot-instructions.md"
    if write_generated(
        instructions_path,
        f"{GENERATED_HEADER}# Lattice — Copilot Instructions\n\n{agents_content[:1500]}",
        force,
    ):
        created.append(".github/copilot-instructions.md")

    instructions_dir = REPO_ROOT / ".github" / "instructions"
    for name, header in [
        ("python.instructions.md", "Python Standards"),
        ("testing.instructions.md", "Testing Standards"),
        ("security.instructions.md", "Security Rules"),
    ]:
        path = instructions_dir / name
        if write_generated(
            path, f"{GENERATED_HEADER}# {header}\n\nSee .github/copilot-instructions.md", force
        ):
            created.append(str(path.relative_to(REPO_ROOT)))

    for skill_name, skill_content in skills.items():
        path = instructions_dir / f"{skill_name}.instructions.md"
        content = f'{GENERATED_HEADER}---\napplyTo: "**"\n---\n\n{skill_content}'
        if write_generated(path, content, force):
            created.append(str(path.relative_to(REPO_ROOT)))

    for agent_name, agent_content in opencode_agents.items():
        if agent_name == "test-fixer":
            path = instructions_dir / "test-fixer.instructions.md"
            content = (
                f"{GENERATED_HEADER}"
                "---\n"
                'applyTo: "**"\n'
                'excludeAgent: "code-review"\n'
                "---\n\n"
                "# Test Fix Agent Instructions\n\n"
                "Use these instructions when asked to run verification, fix failing tests, "
                "repair lint/typecheck failures, or make a branch green.\n\n"
                f"{agent_content}"
            )
            if write_generated(path, content, force):
                created.append(str(path.relative_to(REPO_ROOT)))

    return created


def sync_codex(
    skills: dict[str, str],
    opencode_agents: dict[str, str],
    force: bool,
) -> list[str]:
    created: list[str] = []
    readme_path = REPO_ROOT / ".codex" / "README.md"
    test_fixer = opencode_agents.get("test-fixer", "")
    skills_section = "\n\n".join(skills.values())
    content = (
        f"{GENERATED_HEADER}"
        "# Codex — Lattice\n\n"
        "Use root `AGENTS.md` for project context.\n\n"
        "## Skills\n\n"
        f"{skills_section}\n\n"
        "When asked to make verification pass, follow the Test Fixer contract below.\n\n"
        f"{test_fixer}\n"
    )
    if write_generated(readme_path, content, force):
        created.append(".codex/README.md")
    return created


def main() -> None:
    parser = argparse.ArgumentParser(description="Sync agent configs from OpenCode source")
    parser.add_argument("--force", action="store_true", help="Overwrite existing generated files")
    parser.add_argument(
        "--target",
        choices=["cursor", "claude", "copilot", "codex", "all"],
        default="all",
        help="Target agent (default: all)",
    )
    args = parser.parse_args()

    agents_content = read_agents_md()
    skills = read_opencode_skills()
    opencode_agents = read_opencode_agents()

    targets = ["cursor", "claude", "copilot", "codex"] if args.target == "all" else [args.target]

    created: list[str] = []
    for target in targets:
        if target == "cursor":
            created.extend(sync_cursor(agents_content, skills, opencode_agents, args.force))
        elif target == "claude":
            created.extend(sync_claude(agents_content, skills, opencode_agents, args.force))
        elif target == "copilot":
            created.extend(sync_copilot(agents_content, skills, opencode_agents, args.force))
        elif target == "codex":
            created.extend(sync_codex(skills, opencode_agents, args.force))

    if created:
        print(f"Generated/updated {len(created)} file(s):")
        for path in created:
            print(f"  {path}")
    else:
        print("Nothing to update (all files already exist, use --force to overwrite)")


if __name__ == "__main__":
    main()
